// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0efqPheI9uPr2VbItjCbe_FB-VVMMxqI',
    appId: '1:52118588252:android:d766a401976605ebe10f99',
    messagingSenderId: '52118588252',
    projectId: 'love-reminder-e24c4',
    storageBucket: 'love-reminder-e24c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwIYFWAKyJxfLBOqac511RTVbHO8M8iA8',
    appId: '1:52118588252:ios:dfd2190ad716137ce10f99',
    messagingSenderId: '52118588252',
    projectId: 'love-reminder-e24c4',
    storageBucket: 'love-reminder-e24c4.firebasestorage.app',
    iosBundleId: 'com.example.lovereminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwIYFWAKyJxfLBOqac511RTVbHO8M8iA8',
    appId: '1:52118588252:ios:dfd2190ad716137ce10f99',
    messagingSenderId: '52118588252',
    projectId: 'love-reminder-e24c4',
    storageBucket: 'love-reminder-e24c4.firebasestorage.app',
    iosBundleId: 'com.example.lovereminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8C8AE7plrspq8XQILUoseFKCrCcFHTv8',
    appId: '1:52118588252:web:816b848f19dca7d9e10f99',
    messagingSenderId: '52118588252',
    projectId: 'love-reminder-e24c4',
    authDomain: 'love-reminder-e24c4.firebaseapp.com',
    storageBucket: 'love-reminder-e24c4.firebasestorage.app',
    measurementId: 'G-K7FX7RSXHY',
  );
}
